AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DocVault - Document Management System

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  DBUsername:
    Type: String
    Default: postgres
    NoEcho: true

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Database Password (Min 8 characters)

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    MemorySize: 256

Resources:

  # ============ VPC ============

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub docvault-vpc-${Environment}

  # ============ Subnets ============

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: !Sub docvault-private-1-${Environment}

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: !Sub docvault-private-2-${Environment}

  # ============ Route Table ============

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub docvault-private-rt-${Environment}

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  # ============ S3 Gateway Enpoint ============

  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref VPC
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable

  # ============ Security Groups ============

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda Function
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub docvault-lambda-sg-${Environment}

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for RDS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub docvault-lambda-sg-${Environment}
  
  # ============ RDS ===============

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for Docvault RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub docvault-db-subnet-${Environment}

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub docvault-db-${Environment}
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: "17"
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: docvault
      AllocatedStorage: 20
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      DeletionProtection: false # Setting this on false so that sam delete will be able to delete (in any other real scenario this becomes true)
      Tags:
        - Key: Name
          Value: !Sub docvault-db-${Environment}

  # ============= S3 Bucket ==============

  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub docvault-files-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # LoggingConfiguration: 
      #   DestinationBucketName: !Ref LoggingBucket
      #   LogFilePrefix: !Sub docvault-${Environment}-logs
      Tags:
        - Key: Name
          Value: !Sub docvault-files-${Environment}

  # LoggingBucket:
  #   Type: AWS::S3::Bucket

  DocVaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub docvault-api-${Environment}
      CodeUri: src/
      Handler: docvault.main.handler
      Runtime: python3.13
      MemorySize: 256
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          DATABASE_URL: !Sub postgresql+asyncpg://${DBUsername}:${DBPassword}@${RDSInstance.Endpoint.Address}:5432/docvault
          S3_ENDPOINT: ""
          BUCKET_NAME: !Ref FilesBucket
          AWS_REGION_NAME: !Ref AWS::Region
          SECRET_KEY: !Sub "{{resolve:secretsmanager:docvault-secret-${Environment}:SecretString:secret_key}}"
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref FilesBucket
        - VPCAccessPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:docvault-secret-${Environment}*
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: Any
        RootApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: Any

  MigrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub docvault-migrate-${Environment}
      CodeUri: src/
      Handler: docvault.migrate.handler
      Runtime: python3.13
      MemorySize: 256
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
      Environment:
        Variables:
          DATABASE_URL: !Sub postgresql+asyncpg://${DBUsername}:${DBPassword}@${RDSInstance.Endpoint.Address}:5432/docvault
      Policies:
        - VPCAccessPolicy: {}

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  FunctionName:
    Description: Lambda Function name
    Value: !Ref DocVaultFunction

  BucketName:
    Description: S3 bucket for files
    Value: !Ref FilesBucket

  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address